package com.deng.coder.models;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.tag
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.gmt_create
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.gmt_modify
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    private Long gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.writer_id
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    private Integer writerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.view_account
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    private Integer viewAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.comment_account
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    private Integer commentAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.like_account
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    private Integer likeAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.tag
     *
     * @return the value of article.tag
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.tag
     *
     * @param tag the value for article.tag
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.gmt_create
     *
     * @return the value of article.gmt_create
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.gmt_create
     *
     * @param gmtCreate the value for article.gmt_create
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.gmt_modify
     *
     * @return the value of article.gmt_modify
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public Long getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.gmt_modify
     *
     * @param gmtModify the value for article.gmt_modify
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.writer_id
     *
     * @return the value of article.writer_id
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public Integer getWriterId() {
        return writerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.writer_id
     *
     * @param writerId the value for article.writer_id
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public void setWriterId(Integer writerId) {
        this.writerId = writerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.view_account
     *
     * @return the value of article.view_account
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public Integer getViewAccount() {
        return viewAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.view_account
     *
     * @param viewAccount the value for article.view_account
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public void setViewAccount(Integer viewAccount) {
        this.viewAccount = viewAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.comment_account
     *
     * @return the value of article.comment_account
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public Integer getCommentAccount() {
        return commentAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.comment_account
     *
     * @param commentAccount the value for article.comment_account
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public void setCommentAccount(Integer commentAccount) {
        this.commentAccount = commentAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.like_account
     *
     * @return the value of article.like_account
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public Integer getLikeAccount() {
        return likeAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.like_account
     *
     * @param likeAccount the value for article.like_account
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public void setLikeAccount(Integer likeAccount) {
        this.likeAccount = likeAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbg.generated Wed Oct 23 13:46:40 GMT+08:00 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}